# Generated by Django 3.2.9 on 2021-12-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('date_of_joining', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('gender', models.CharField(default=None, max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('reporting_manager', models.CharField(max_length=50)),
                ('emp_image', models.ImageField(blank=True, default='', upload_to='static/app1/images')),
                ('password', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
