# Generated by Django 3.2.9 on 2021-12-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_employee_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.IntegerField(default='123456789'),
        ),
    ]
